# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ee528e54-8087-47dd-b1dc-9ade358e73a0";
      fsType = "btrfs";
      options = [ "subvol=@" "compress-force=zstd:1" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/ee528e54-8087-47dd-b1dc-9ade358e73a0";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress-force=zstd:1" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ee528e54-8087-47dd-b1dc-9ade358e73a0";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress-force=zstd:1" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/ee528e54-8087-47dd-b1dc-9ade358e73a0";
      fsType = "btrfs";
      options = [ "subvol=@var" "compress-force=zstd:1" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
