# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "ahci" "nvme" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/cb2c2975-6f3b-4e61-99e7-d21894f12bd0";
      fsType = "btrfs";
      options = [ "subvol=@" "compress-force=zstd:3" "noatime" ];
    };

  boot.initrd.luks.devices."luks".device = "/dev/disk/by-uuid/67100940-d84d-4355-912d-a010eefe85b9";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/cb2c2975-6f3b-4e61-99e7-d21894f12bd0";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress-force=zstd:3" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/cb2c2975-6f3b-4e61-99e7-d21894f12bd0";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress-force=zstd:3" "noatime" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/cb2c2975-6f3b-4e61-99e7-d21894f12bd0";
      fsType = "btrfs";
      options = [ "subvol=@swap" "compress-force=zstd:3" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BD0C-5BD3";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
