# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "ehci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/716d9b61-538e-42b5-a81d-e6d425829fd8";
      fsType = "btrfs";
      options = [ "subvol=@" "compress-force=zstd:1" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/716d9b61-538e-42b5-a81d-e6d425829fd8";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress-force=zstd:1" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/716d9b61-538e-42b5-a81d-e6d425829fd8";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress-force=zstd:1" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/716d9b61-538e-42b5-a81d-e6d425829fd8";
      fsType = "btrfs";
      options = [ "subvol=@var" "compress-force=zstd:1" ];
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/716d9b61-538e-42b5-a81d-e6d425829fd8";
      fsType = "btrfs";
      options = [ "subvol=@data" "compress-force=zstd:1" ];
    };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/509D-A9C9";
      fsType = "vfat";
    };

  fileSystems."/smb" =
    { device = "/dev/disk/by-uuid/f23ec2c5-dda2-4426-bc32-b29f62fc4cac";
      fsType = "btrfs";
      options = [ "subvol=@smb" "compress-force=zstd:1" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0f1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
